# Generated by Django 5.2.6 on 2025-12-03 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deportivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('motor', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('imagen_url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ford100Anios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor', models.CharField(max_length=100)),
                ('color', models.CharField(default='Azul Centenario', max_length=50)),
                ('rines', models.CharField(max_length=100)),
                ('emblemas', models.CharField(max_length=200)),
                ('interior', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('disponible', models.BooleanField(default=True)),
                ('imagen_url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PickUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('motor', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('imagen_url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SUV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('motor', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('imagen_url', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(max_length=50)),
                ('producto_id', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('efectivo', 'Efectivo')], max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_pago', models.CharField(default='Exitoso', max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
